/* No secrets in localStorage; authentication uses an HttpOnly same-site cookie. */
const $=id=>document.getElementById(id);
let current=null,onlyNeeds=false,staff=sessionStorage.getItem('vn_staff')||'Staff',active=null,runtime={autoRepliesEnabled:false},conversations=[],page='Inbox',statusFilter='all';
const fields=['name','channel_handle','email','phone','location','tags','preferred_contact','language','subject','jewelry_type','important_elements','references','gemstone_preference','budget','occasion','required_date','preferences','final_quote','payment_status','deposit_status','production_status','feasibility','designer_notes','timeline_status','suggested_price'];
const stages=['NEW','EXPLORING','DESIGN_DIRECTION','QUALIFIED','DESIGNER_REVIEW','QUOTED','DEPOSIT_PENDING','DEPOSIT_PAID','DESIGN_REFINEMENT','DESIGN_APPROVED','IN_PRODUCTION','FINAL_REVIEW','REVISION','READY_TO_SHIP','SHIPPED','DELIVERED','AFTERCARE'];
for(const [id,values] of [['factKey',fields],['stageTarget',stages]]) for(const v of values){const o=document.createElement('option');o.value=v;o.textContent=v.replaceAll('_',' ');$(id).append(o);}
async function api(path,body){const r=await fetch('/admin'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-Staff-Name':staff},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed');return data;}
function notice(text){$('notice').textContent=text;}
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
async function busy(fn){const buttons=[...document.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{notice('Working…');await fn();notice('Saved.');}catch(e){notice(e.message);}finally{buttons.forEach(b=>b.disabled=false);}}
function renderRuntime(){const on=runtime.autoRepliesEnabled===true;$('sidebarStatus').textContent='Emily · '+(on?'LIVE':'PAUSED');$('sidebarDot').classList.toggle('on',on);$('runtimeDot').classList.toggle('on',on);$('runtimeTitle').textContent=on?'Emily auto-replies are LIVE':'Emily auto-replies are PAUSED';$('runtimeMeta').textContent=on?'Safe live-channel messages may be answered automatically. CONSULT / REVIEW / HUMAN rules still apply.':'Live channel sending is off. Incoming conversations can still be collected and reviewed.';$('runtimeToggle').textContent=on?'Pause all auto-replies':'Enable auto-replies';$('runtimeToggle').className=on?'danger':'primary';if(runtime.updatedAt)$('runtimeMeta').textContent+=` Last changed by ${runtime.updatedBy||'staff'} · ${new Date(runtime.updatedAt).toLocaleString()}.`;}
async function loadRuntime(){runtime=await api('/api/runtime');$('runtimeBar').classList.remove('hidden');renderRuntime();}
async function inbox(){const data=await api('/api/conversations');conversations=data.conversations;$('login').classList.add('hidden');$('sidebar').classList.remove('hidden');$('logout').classList.remove('hidden');$('staffName').textContent=staff;$('staffAvatar').textContent=staff.charAt(0).toUpperCase();$('count').textContent=conversations.filter(c=>c.needs_human).length;renderInbox();await showPage(page);}
function conversationStatus(c){return c.needs_human?'waiting':['DELIVERED','AFTERCARE'].includes(c.stage)?'resolved':'open';}
function renderInbox(){const q=$('search').value.trim().toLowerCase();$('inbox').replaceChildren();const visible=conversations.filter(c=>(!onlyNeeds||c.needs_human)&&(statusFilter==='all'||conversationStatus(c)===statusFilter)&&(!q||(c.name+' '+c.stage+' '+c.mode).toLowerCase().includes(q)));for(const c of visible){const b=el('button',undefined,'inbox-item'+(c.id===current?' selected':''));b.append(el('strong',(c.demo?'[DEMO] ':'')+c.name),el('small',journeyLabels[journeyIndex(c.stage)]||c.stage),el('span',conversationStatus(c),'badge'+(c.needs_human?' warning':'')),el('small',c.mode+' · '+c.unread+' unread'));b.onclick=()=>busy(()=>open(c.id));$('inbox').append(b);}if(!visible.length)$('inbox').append(el('p','No conversations match this view.','empty'));}
async function open(id){current=id;renderInbox();active=await api('/api/conversations/'+id);const s=active,c=s.conversation;$('clientTitle').textContent=(c.demo?'[DEMO] ':'')+c.name;$('controls').classList.remove('hidden');$('factControls').classList.remove('hidden');$('modeLabel').textContent=c.mode+(c.owner?' · '+c.owner:'');$('humanForm').classList.toggle('hidden',c.mode!=='HUMAN');$('briefing').textContent=`Customer intent: ${s.briefing.intent}\nDecision needed: ${s.briefing.decisionNeeded}\n${s.briefing.keyFacts.slice(0,8).join('\n')}`;
 for(const key of ['thread','notes'])$(key).replaceChildren();for(const m of s.messages){if(m.role==='system')continue;const b=el('div',undefined,'bubble '+m.role);b.append(el('small',`${m.role.replaceAll('_',' ')} · ${m.delivery} · ${new Date(m.created_at).toLocaleString()}`),el('div',m.content));$(m.role==='human_internal'?'notes':'thread').append(b);}
 $('facts').replaceChildren();const dl=el('dl',undefined,'facts');for(const key of fields){const f=s.facts.find(f=>f.key===key);dl.append(el('dt',key.replaceAll('_',' ')));const dd=el('dd',f?typeof f.value==='string'?f.value:JSON.stringify(f.value):'—');if(f){dd.append(el('div',`${f.source}${f.confirmed?' · confirmed':''}`,'muted'));dd.title=f.evidence;}dl.append(dd);}$('facts').append(dl);$('stageLabel').textContent=c.stage;renderClient(s);
 $('reviews').replaceChildren();for(const r of s.reviews.slice(0,5)){const box=el('div',undefined,'review');box.append(el('h3','Emily draft · '+r.status));const t=el('textarea');t.value=(r.edited||r.draft).join('\n\n');t.setAttribute('aria-label','Edit Emily draft');box.append(t);if(r.status==='pending'&&c.mode==='REVIEW'){const b=el('button','Approve edited reply (store only)','primary');b.onclick=()=>busy(async()=>{await api(`/api/conversations/${id}/reviews/${r.id}/approve`,{messages:t.value.split(/\n\s*\n/).filter(Boolean)});await refresh();});box.append(b);}else t.readOnly=true;$('reviews').append(box);}
 $('audit').replaceChildren();for(const a of s.audit)$('audit').append(el('p',`${a.event.replaceAll('_',' ')} · ${a.actor} · ${new Date(a.created_at).toLocaleString()}`,'muted'));await api('/api/conversations/'+id+'/read',{});
}
async function refresh(){await Promise.all([inbox(),loadRuntime()]);if(current)await open(current);}
$('loginForm').onsubmit=e=>{e.preventDefault();busy(async()=>{staff=$('staff').value.trim();await api('/login',{token:$('token').value});sessionStorage.setItem('vn_staff',staff);$('token').value='';await Promise.all([inbox(),loadRuntime()]);});};
$('logout').onclick=()=>busy(async()=>{await api('/logout',{});sessionStorage.removeItem('vn_staff');location.reload();});
$('runtimeToggle').onclick=()=>{const enabling=!runtime.autoRepliesEnabled;const prompt=enabling?'Enable Emily auto-replies for live channel adapters? Safe messages may be sent automatically.':'Pause ALL Emily auto-replies? Incoming messages will still be collected.';if(!confirm(prompt))return;busy(async()=>{runtime=await api('/api/runtime/auto-replies',{enabled:enabling});renderRuntime();});};
$('refresh').onclick=()=>busy(refresh);$('filter').onclick=()=>busy(async()=>{onlyNeeds=!onlyNeeds;$('filter').classList.toggle('primary',onlyNeeds);await inbox();});
$('createForm').onsubmit=e=>{e.preventDefault();busy(async()=>{const c=await api('/api/conversations',{name:$('newName').value,demo:$('demo').checked});await inbox();await open(c.id);});};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>busy(async()=>{await api(`/api/conversations/${current}/mode`,{mode:b.dataset.mode});await refresh();}));
for(const [form,path,body,clear] of [
 ['customerForm','customer',()=>({message:$('customerText').value,externalId:crypto.randomUUID()}),'customerText'],
 ['humanForm','human-send',()=>({message:$('humanText').value}),'humanText'],
 ['noteForm','notes',()=>({note:$('noteText').value,designerConfirmed:$('confirmed').checked,feasibility:$('feasibility').value,timeline_status:$('timeline').value,suggested_price:$('suggested').value}),'noteText'],
 ['factForm','facts',()=>({key:$('factKey').value,value:$('factValue').value,evidence:$('factEvidence').value}),null],
 ['stageForm','stage',()=>({stage:$('stageTarget').value,evidence:$('stageEvidence').value}),null]
])$(form).onsubmit=e=>{e.preventDefault();busy(async()=>{await api(`/api/conversations/${current}/${path}`,body());if(clear)$(clear).value='';await refresh();});};

const journeyLabels=['Initial Chat','Design Discussion','Design Approved','Deposit Collection','Production','Shipping','Collected'];
const journeyGroups=[['NEW','EXPLORING'],['DESIGN_DIRECTION','QUALIFIED','DESIGNER_REVIEW','QUOTED','DESIGN_REFINEMENT'],['DESIGN_APPROVED'],['DEPOSIT_PENDING','DEPOSIT_PAID'],['IN_PRODUCTION','FINAL_REVIEW','REVISION','READY_TO_SHIP'],['SHIPPED'],['DELIVERED','AFTERCARE']];
function journeyIndex(stage){return journeyGroups.findIndex(g=>g.includes(stage));}
function factValue(s,key){const f=s.facts.find(f=>f.key===key);return f?(typeof f.value==='string'?f.value:JSON.stringify(f.value)):null;}
function factsList(target,items){const dl=el('dl',undefined,'facts');for(const [label,value] of items){dl.append(el('dt',label),el('dd',value||'Not recorded'));}$(target).replaceChildren(dl);}
function renderReferences(target,refs){$(target).replaceChildren();for(const r of refs){const tile=el('div',undefined,'ref-tile');tile.append(el('div','▧','ref-placeholder'),el('strong',r.name));let safe=false;try{safe=new URL(r.url).protocol==='https:';}catch{}if(safe){const a=el('a','Open reference ↗');a.href=r.url;a.target='_blank';a.rel='noopener noreferrer';tile.append(el('br'),a);}else tile.append(el('p','Placeholder · no file linked','muted'));tile.append(el('div',r.reviewed_at?'Review recorded':'Not marked reviewed','muted'));$(target).append(tile);}if(!refs.length){for(const label of ['Photos & inspiration','Sketches & materials']){const tile=el('div',undefined,'ref-tile');tile.append(el('div','▧','ref-placeholder'),el('span',label),el('div','No files yet','muted'));$(target).append(tile);}}}
function renderClient(s){const c=s.conversation,f=k=>factValue(s,k);$('profileName').textContent=c.name;$('clientAvatar').textContent=c.name.charAt(0).toUpperCase();$('profileChannel').textContent=[f('channel_handle')||c.handle,c.channel,c.demo?'Demo record':null].filter(Boolean).join(' · ');factsList('quickFacts',[['Email',f('email')],['Phone',f('phone')],['Location',f('location')],['Customer since',new Date(c.created_at).toLocaleDateString()],['Tags',f('tags')]]);factsList('quickInfo',[['Interest',f('jewelry_type')||f('subject')],['Budget',f('budget')],['Target date',f('required_date')],['Contact',f('preferred_contact')]]);factsList('orderFacts',[['Final quote',f('final_quote')],['Deposit',f('deposit_status')],['Payment',f('payment_status')],['Production',f('production_status')],['Timeline',f('timeline_status')]]);$('journey').replaceChildren();const index=journeyIndex(c.stage);journeyLabels.forEach((label,i)=>{const li=el('li',undefined,i<index?'done':i===index?'current':'');if(i===index)li.setAttribute('aria-current','step');li.append(el('span',i<index?'✓':String(i+1),'step'),el('span',label));$('journey').append(li);});$('internalStage').textContent='Internal stage: '+c.stage+' · view only';renderReferences('referencePreview',s.references.slice(0,2));renderReferences('referenceFiles',s.references);$('referenceControls').classList.remove('hidden');$('privateNotes').replaceChildren();for(const m of s.messages.filter(m=>m.role==='human_internal'))$('privateNotes').append(el('div',m.content,'bubble human_internal'));if(!$('privateNotes').children.length)$('privateNotes').append(el('p','No private notes yet.','muted'));}
function activateTab(name){document.querySelectorAll('[data-tab]').forEach(b=>{const selected=b.dataset.tab===name;b.classList.toggle('active',selected);b.setAttribute('aria-selected',String(selected));});for(const id of ['info','order','references','notes'])$('tab-'+id).classList.toggle('hidden',id!==name);}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>activateTab(b.dataset.tab));
$('search').oninput=renderInbox;
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{statusFilter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderInbox();});
$('mobileMenu').onclick=()=>{const isOpen=$('sidebar').classList.toggle('open');$('mobileMenu').setAttribute('aria-expanded',String(isOpen));};
function metric(label,value){const card=el('div',undefined,'panel metric');card.append(el('strong',String(value)),el('span',label,'muted'));return card;}
function records(target,list){const wrap=el('div',undefined,'record-list');for(const c of list){const b=el('button');b.append(el('strong',(c.demo?'[DEMO] ':'')+c.name),el('span',(journeyLabels[journeyIndex(c.stage)]||c.stage)+' · '+c.mode,'muted'));b.onclick=()=>busy(async()=>{await showPage('Inbox');await open(c.id);});wrap.append(b);}if(!list.length)wrap.append(el('p','No records in this view yet.','empty'));target.append(wrap);}
async function showPage(next){page=next;$('pageTitle').textContent=next==='Media Library'?'Media Library / References':next;$('workspace').classList.toggle('hidden',next!=='Inbox');$('sectionView').classList.toggle('hidden',next==='Inbox');document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===next));$('sidebar').classList.remove('open');$('mobileMenu').setAttribute('aria-expanded','false');if(next==='Inbox')return;const root=$('sectionView');root.replaceChildren();root.append(el('h1',next));
if(next==='Dashboard'||next==='Analytics'){root.append(el('p','A live overview of the latest 200 conversation records, including labeled demos.','muted'));const grid=el('div',undefined,'metric-grid');grid.append(metric('Conversations',conversations.length),metric('Waiting for team',conversations.filter(c=>c.needs_human).length),metric('In production',conversations.filter(c=>journeyIndex(c.stage)===4).length),metric('Collected',conversations.filter(c=>journeyIndex(c.stage)===6).length));root.append(grid);if(next==='Analytics'){const box=el('div',undefined,'panel info-block');box.append(el('h3','Client journey distribution'));journeyLabels.forEach((label,i)=>box.append(el('p',label+' — '+conversations.filter(c=>journeyIndex(c.stage)===i).length)));root.append(box);}else{root.append(el('h3','Conversations needing your judgment'));records(root,conversations.filter(c=>c.needs_human));}}
else if(next==='Customers'||next==='Orders'){root.append(el('p',next==='Customers'?'Open a client to view confirmed memory, references and private notes.':'Commission stages come from the authoritative lifecycle. Open a record to review evidence.','muted'));records(root,conversations);}
else if(next==='Knowledge Base'){const data=await api('/api/knowledge');if(page!==next)return;root.append(el('div',data.content,'panel info-block'));}
else if(next==='Media Library'){root.append(el('p','References are organized by client. Choose a client to open their saved links, photos and material placeholders.','muted'));const wrap=el('div',undefined,'record-list');for(const c of conversations){const b=el('button',c.name+' · Open references');b.onclick=()=>busy(async()=>{await showPage('Inbox');await open(c.id);activateTab('references');});wrap.append(b);}root.append(wrap);if(!conversations.length)root.append(el('p','Create a client conversation to begin collecting references.','empty'));}
else if(next==='Settings'){const box=el('div',undefined,'panel info-block');box.append(el('h3','Emily & the team'),el('p','The global LIVE / PAUSED control above uses saved Postgres state. Conversation-level CONSULT, REVIEW and HUMAN safeguards still apply.'),el('h3','Access & privacy'),el('p','Signed in as '+staff+'. Admin-token authentication protects the private workspace. Your staff name is recorded for audit attribution.'),el('h3','Channels'),el('p','Instagram sending and Shopify lookups are not connected here. Approved messages are stored for delivery; simulated messages are internal tests.'),el('h3','Inbox filters'),el('p','Waiting means the conversation needs human input. Resolved means DELIVERED or AFTERCARE with no pending human input. Open contains the remaining records. These views do not change lifecycle state.'));root.append(box);}}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>busy(()=>showPage(b.dataset.page)));
$('referenceForm').onsubmit=e=>{e.preventDefault();busy(async()=>{await api('/api/conversations/'+current+'/references',{name:$('referenceName').value,url:$('referenceUrl').value});$('referenceName').value='';$('referenceUrl').value='';await open(current);});};
inbox().then(loadRuntime).catch(()=>notice('Sign in to view the private studio.'));
